// Code generated by hertz generator.

package main

import (
	"GoYin/server/service/api/config"
	"GoYin/server/service/api/initialize"
	"GoYin/server/service/api/initialize/rpc"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/hertz-contrib/pprof"
)

func main() {
	// initialize
	initialize.InitLogger()
	r, info := initialize.InitNacos()
	initialize.InitMinio()
	tracer, cfg := hertztracing.NewServerTracer()
	rpc.Init()
	// create a new server
	h := server.New(
		tracer,
		server.WithHostPorts(fmt.Sprintf(":%d", config.GlobalServerConfig.Port)),
		server.WithRegistry(r, info),
		server.WithHandleMethodNotAllowed(true),
	)
	// use pprof & tracer mw
	pprof.Register(h)
	h.Use(hertztracing.ServerMiddleware(cfg))
	register(h)
	h.Spin()
}
